#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: apiback-auth-tls
#  namespace: apiback
#spec:
#  entryPoints:
#    - websecure
#  routes:
#    - kind: Rule
#      match: Host(`apiback.telecomita.demo.traefiklabs.tech`) && Path(`/newline`) && Method(`POST`)
#      services:
#        - name: apiback-v1
#          port: 80
#      middlewares:
#        - name: jwt-auth-admin
#  tls:
#    certResolver: default
